seed: 42
device: cpu

# Experiment (ks, kolmogorov)
exp_dir: kolmogorov/Re34
input_dim: 2
output_dim: 2
n_dim: 2
domain_size:
  - 1
  - 1
ratio: 10

# Model parameters
modes_separation: 
  - 12
norm_separation: L2
representation_dim: 1
n_heads: 2
n_attblocks: 1
hidden_dim: 8
dropout: 0.2
layer_norm: true


# Training parameters
num_epochs: 500
seq_length: 10
batch_size: 32
num_workers: 4
loss_fn: mse 
optimizer: 
  type: adam
  lr: 0.01
  wd: 1.
scheduler:
  name: cosine_annealing
  T_max: 500
  eta_min: 0.0001
early_stopping_patience: 30
early_stopping_delta: 1e-4
metrics:
  - rmse
  - mae
  - relative_rmse # relative rmse
  - relative_mae # relative l1 norm


#
exp_name: exp4
name_weigths_to_load: null

